# -*- coding: utf-8 -*-
"""Mind reader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dReKv9mIkX3bRnPAUPgf_12Nb0LgzZyz
"""

import random

random_num_list = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
random_num = random.choice(random_num_list)

print("Guess a number from 1 to 9, and don't tell me.")
input("Press Enter to continue...")
print("Double the number you guess.")
input("Press Enter to continue...")
print(f"Add {random_num} to that number")
input("Press Enter to continue...")
print(f"Now make it half or divide by 2, so the number will be {random_num / 2}")
input("Press Enter to continue...")
print("Remove or deduct the number you guessed at the beginning.")
input("Press Enter to continue...")
print(f"Now you have left {random_num / 2} number, correct :)")

# import random

# print("Guess a number from 1 to 9, and don't tell me.")
# input("Press Enter to continue...")
# print("Double the number you guess.")
# input("Press Enter to continue...")
# random_num = random.randint(1, 100) * 2  # Generate a random even number
# print(f"Add {random_num} to that number")
# input("Press Enter to continue...")
# print(f"Now make it half or divide by 2")
# input("Press Enter to continue...")
# print("Remove or deduct the number you guessed at the beginning.")
# input("Press Enter to continue...")
# print(f"Now you have left {random_num / 2} number, correct :)")



import random

random_num_list = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
random_num = random.choice(random_num_list)

print("Guess a number from 1 to 9, and don't tell me.")
input("Press Enter to continue...")
print("Double the number you guess.")
input("Press Enter to continue...")
print(f"Add {random_num} to that number")
input("Press Enter to continue...")
print(f"Now make it half or divide by 2")
input("Press Enter to continue...")
print("Remove or deduct the number you guessed at the beginning.")
input("Press Enter to continue...")
print(f"Now you have left {random_num / 2} , correct :)")